# Example Site settings

#google_analytics: UA-NNNNNNNN-N

properties:
  title: "@themost-framework"

header_pages:
 - index.md
 - about.md

footer: 'follow us on <a href="https://github.com/themost-framework">github</a>'

style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
